version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: githw-app:latest
    container_name: app

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: githw-web:latest
    ports:
      - "80:80"
    depends_on:
      app:
        condition: service_completed_successfully
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
